# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -o artifacts/api ./cmd/main.go

    - name: Archive #
      uses: actions/upload-artifact@v4
      with:
        name: api #
        path: artifacts
